### ISSUE TITLE
slight jumping when all steps are checked

### ISSUE THREAD

**Issue by root-ansh** [params-ing/StepViewAndroid#14]
imgur [link1](https://imgur.com/a/lkM9uBg) / [alternative](https://i.imgur.com/8ycJYr2.mp4)

**Comment by params-ing** [comment]
Can you please past heere the code to reproduce this? Thanks

**Comment by root-ansh** [comment]
I am currently using a recyclerview to create a stepper like this , so not sure if i have the repro code lying around. but as far as i remember it happened with the default usage ( just adding the view in a empty activity and changing stepper state on button click) . I will close this issue for now. thankyou for this awesome library!
