### ISSUE TITLE
setstatuslist

### ISSUE THREAD

**Issue by NKTina** [params-ing/StepViewAndroid#2]
i have dynamic entries and wanted to set the status in code.. i found setstatuslist but it's not working.. help :)

**Comment by params-ing** [comment]
I will check that

**Comment by NKTina** [comment]
any news on this?

**Comment by params-ing** [comment]
Hi Tina, I will be posting an update by Monday. Things got busy, Sorry for the delay :)

**Comment by TadesseAngaw** [comment]
Any update on this issue?

**Comment by params-ing** [comment]
This has now been fixed. Please update the version to 1.0.2.
